### PR TITLE
Add ts defination

### PR DESCRIPTION
**Pull request by MrMeison**
Add typescript definition files for project
the webrtcsupport definition can be removed when pull request ( https://github.com/HenrikJoreteg/webrtcsupport/pull/27 ) will be merged.

### CODE REVIEW

**Comment by tgabi333** [comment]
Thank for PR. Do we need to declare `@types/webrtc` and `@types/socket.io-client`as a dependency?

**Comment by MrMeison** [comment]
Yes. I follow this instruction: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html 
```@types/webrtc``` using for getting declaration file for ```RTCPeerConnection``` and ```@types/socket.io-client``` for socket.io connection

**Comment by tgabi333** [comment]
For someone not using typescript, these packages are unnecessary. They are
not real dependencies.

However we can put a section into the documentation how to use it with
typescript.

Anyway, there was a lot of undocumented changes in socket.io, using v1.3
and providing v1.4 types makes me feel uncomfortable.

On Feb 7, 2017 21:20, "Konstantin Mamaev" <notifications@github.com> wrote:

Yes. I follow this instruction: https://www.typescriptlang.
org/docs/handbook/declaration-files/publishing.html
@types/webrtc using for getting declaration file for RTCPeerConnection and
@types/socket.io-client for socket.io connection

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/andyet/SimpleWebRTC/pull/544#issuecomment-278127807>,
or mute the thread

**Comment by MrMeison** [comment]
I removed ```@types``` dependencies. 
Can you check for compliance documentation my declaration file?  I used doc sections, example page ( https://simplewebrtc.com/notsosimple.html ) and source code for the definition for library events and methods. 

> Anyway, there was a lot of undocumented changes in socket.io, using v1.3
> and providing v1.4 types makes me feel uncomfortable.

All right, but I use only declaration file and problems may arise only if the socket.io API was changed.

**Comment by tgabi333** [comment]
@MrMeison webrtcsupport definition should go here: https://github.com/HenrikJoreteg/webrtcsupport

**Comment by MrMeison** [comment]
@tgabi333, yes, I send pull request for it ( https://github.com/HenrikJoreteg/webrtcsupport/pull/27), but that project not been updated for a long time and I don't think, it will be accepted soon

**Comment by MrMeison** [comment]
@tgabi333, I removed webrtcsupport declaration files and changed file link to types link for it

**Comment by MrMeison** [comment]
Could you please update status for this PR?

**Comment by xdumaine** [comment]
@MrMeison @tgabi333 I'm not familiar with TypeScript, but if you're good to go on this, I'll merge it. @MrMeison could you just double check that it's still good? Some of the project structure changed slightly.

**Comment by xdumaine** [comment]
@MrMeison I'm going to close this since there's been no activity, and I can't verify it's still valid. Sorry it never got merged when you opened it 🙁

**Pull request closed without merging**
