### PR TITLE
leave room, but can't end all peers.

### PR DESCRIPTION
**Pull request by lingfei-zhang**

### CODE REVIEW

**Comment by tgabi333** [comment]
Or you can just copy peers array like: 

```
this.webrtc.peers.slice(0).forEach(function (peer) {
    if (peer.broadcaster) {
        peer.end();
    }
});
```

**Comment by xdumaine** [comment]
@lingfei-zhang could you clarify the problem that this solves?

**Comment by tgabi333** [comment]
@xdumaine Every time you call peer.end a callback modify the array you are currenty walking through (foreach) which will not itearate all elements.

**Comment by tgabi333** [comment]
Imo this way (publishing an array property) is wrong by design.

**Comment by tgabi333** [comment]
This is still a valid issue.

**Comment by fippo** [comment]
i'll see when I have time to merge this.

**Comment by xdumaine** [comment]
IMO, the suggestion in @tgabi333's comment above is better. I'd prefer that, as it terminates, and doesn't cause a potentially blocking loop should `peer.end()` fail to remove the peer from the array.

**Comment by fippo** [comment]
how is #176?

**Pull request closed without merging**
