### PR TITLE
test: update tests to use webdriver lib from testbed

### PR DESCRIPTION
**Pull request by fippo**
which also pulls selenium + friends from that package.
Also installs chrome/firefox via travis-multirunner and uses
those versions.

### CODE REVIEW

**Comment by fippo** [comment]
I was somewhat surprised that I couldn't pull in selenium from the testbed repository... that has worked well in the past but npm@5...

**Comment by fippo** [comment]
the remaining hang is caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1332122

**Comment by fippo** [comment]
ah... so the issue was the bver was not set, leading to the version of chrome/firefox installed with travis multirunner not being used.

@tgabi333 @xdumaine can you take a look? (once I squashed)

**Comment by xdumaine** [comment]
Looks good to me. Thanks for the work on this!

**Pull request merged**
