### PR TITLE
updating localmedia, rtcpeerconnection, browserify, express, precommi…

### PR DESCRIPTION
**Pull request by bitnovus**
…t-hook, request, selenium, and uglify

Hey andyet,

You guys are pretty awesome. In this commit, I bumped up all the dependencies except for socket.io-client since @fippo pinned it to 1.3.7. The syntax for browserify changed a tad bit so I updated build.js to reflect the changes since 2.22.0.

Latest master branch is incorporated.
JSHint looks happy.
All the current tests pass.
There are no new tests.

I hope this helps!

Best,
Daniel

### CODE REVIEW

**Comment by tgabi333** [comment]
:+1

As i see `request` package is not used anymore, can be removed from devDependencies

**Comment by fippo** [comment]
LGTM -- I need to make some other updates, will merge this and publish a new npm version afterwards

**Comment by fippo** [comment]
oh wait... @latentflip @nlf can someone give me back my access rights please?

**Comment by fippo** [comment]
published as 2.2.0 -- there is something exciting going on, too

**Pull request merged**
