### PR TITLE
Allow running from a non-http source

### PR DESCRIPTION
**Pull request by xvobl**
Changed the jquery reference to include 'http:' before the '//' to allow running from another protocol.

### CODE REVIEW

**Comment by xdumaine** [comment]
Hmm, shouldn't need this. The point of leaving off the protocol is so that the request matches the protocol used to serve the site.

**Comment by xvobl** [comment]
Exactly – if the site isn't served with http, then it won't access the jquery host correctly. For example, ftp://example.com/SimpleWebRTC/index.html will try to access ftp://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js rather than http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js.

**Comment by fippo** [comment]
Chrome doesn't allow getUserMedia from non-https sites to this should be https imo

**Comment by xvobl** [comment]
Whoops. You're totally right – I've changed it

**Pull request merged**
