### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by skade**

### CODE REVIEW

**Comment by fippo** [comment]
whoops, thanks!

**Comment by xdumaine** [comment]
Hey @skade thanks for the PR! This must mean you were reading the docs 😉 please let us know if anything is unclear or could be improved, and PRs are most welcome. Happy video chatting!

**Comment by skade** [comment]
@xdumaine I was just searching for a way to do local video recording and haven't found anything :). (Only hints in the advanced examples: https://simplewebrtc.com/notsosimple.html -> recording)

But still, I correct errors when I find them :).

**Comment by Hirtenknogger** [comment]
@skade You can use the MediaRecorder API (https://www.w3.org/TR/mediastream-recording/) to record WebRTC Streams.

**Pull request merged**
