### PR TITLE
pin socket.io to 1.3.7

### PR DESCRIPTION
**Pull request by fippo**
easiest way to solve the apparent breakage of 1.4.x until someone with more interest in updating and maintaining this steps up.

### CODE REVIEW

**Comment by fippo** [comment]
hrmpf. what did I say about update-bundle-after-merge...

**Comment by fippo** [comment]
published as 2.1.1

**Comment by xdumaine** [comment]
@fippo who has merge rights to both SimpleWebRTC *and* signalmaster? I don't  have signalmaster.

**Comment by fippo** [comment]
@nlf just gave them to me. And apparently I am maintaining a npm package for it even. Not that I know how/why but...

**Comment by dkaminski** [comment]
@fippo thanks for getting this fixed in both SimpleWebRTC and Signalmaster. I spent a lot of time trying to fix / work around the socket.io problems to no avail, so I personally really appreciate it.

**Pull request merged**
