### PR TITLE
fix stopping screen stream for chrome 47+

### LINKED ISSUE #363: Chrome 47.  stream.stop is not a function
Hey, just noticed this on Chrome 47
```
SimpleWebRTC.prototype.stopScreenShare = function () {
    this.connection.emit('unshareScreen');
    var videoEl = document.getElementById('localScreen');
    var container = this.getRemoteVideoContainer();
    var stream = this.getLocalScreen();

    if (this.config.autoRemoveVideos && container && videoEl) {
        container.removeChild(videoEl);
    }

    // a hack to emit the event the removes the video
    // element that we want
    if (videoEl) this.emit('videoRemoved', videoEl);
    if (stream) stream.stop();                                                   <--------------------------
    this.webrtc.peers.forEach(function (peer) {
        if (peer.broadcaster) {
            peer.end();
        }
    });
```

I was doing something like this in my UI code  self.shareScreen is a button handler.
```
  self.shareScreen = function(enabled) {
    if (enabled) {
      if (self.webrtc.getLocalScreen()) self.webrtc.stopScreenShare(); // unshare
```

### PR DESCRIPTION
**Pull request by xdumaine**
Fixes #363 @fippo @legastero

### CODE REVIEW

**Comment by tgabi333** [comment]
Is that backward compatible?

**Comment by xdumaine** [comment]
@tgabi333 [localMedia](https://github.com/otalk/localmedia/blob/master/index.js) which is used by SimpleWebRTC for the majority of stream management and actions is already exclusively using `track.stop` - This would be a minor version bump, so consumers needing `stream.stop` should use older versions of both.

**Comment by tgabi333** [comment]
@xdumaine thank you for explanation.

**Comment by fippo** [comment]
i think both chrome and firefox implemented getTracks and track.stop for 2+ years

+1

**Comment by xdumaine** [comment]
Published in 2.1.0

**Pull request merged**
