### PR TITLE
Organized, updated adapter, changed build, updated other otalk modules

### PR DESCRIPTION
**Pull request by xdumaine**
- Default output excludes adapter.js
- simplewebrtc-with-adapter.bundle.js is available for one file import
- Drop express/server.js/fake keys for stupid-server (one-command https server)
- Move source into src and output to out
- Some fixes for updated dependencies

### CODE REVIEW

**Comment by fippo** [comment]
i'd just bump the major

**Comment by xdumaine** [comment]
Yep this'll be a major version bump here.

**Comment by fippo** [comment]
ah... latest-v2 simply got killed. Yay :-)

**Comment by xdumaine** [comment]
@fippo Fixed the tests for chrome, but they still fail in firefox. I remember something about selenium tests not working there. Should they for this project?

**Comment by xdumaine** [comment]
Alright, all tests current run locally. Good enough for me.

**Comment by fippo** [comment]
oh yes the marionette issue... can you try buildDriver from https://github.com/fippo/testbed/blob/master/webdriver.js ?

**Comment by xdumaine** [comment]
Alright, unfortunately I'm not sure what's up the tests failing in Travis, and I don't have time to fight with with it. Going to merge and release this unless there are objections.

**Pull request merged**
